# Generated by Django 3.1.7 on 2021-02-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('ml_id', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLDescriptionTpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProviderTpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('title_css', models.CharField(blank=True, max_length=100, null=True)),
                ('description_css', models.CharField(blank=True, max_length=100, null=True)),
                ('toc_css', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_css', models.CharField(blank=True, max_length=100, null=True)),
                ('author_css', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_css', models.CharField(blank=True, max_length=100, null=True)),
                ('language_css', models.CharField(blank=True, max_length=100, null=True)),
                ('category_css', models.CharField(blank=True, max_length=100, null=True)),
                ('tags_css', models.CharField(blank=True, max_length=100, null=True)),
                ('student_count_css', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_count_css', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_top_5_css', models.CharField(blank=True, max_length=100, null=True)),
                ('year_css', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('content_type', models.CharField(blank=True, choices=[('a', 'Audio'), ('v', 'Video'), ('b', 'Book')], max_length=1, null=True)),
                ('photo_logo', models.ImageField(upload_to='')),
                ('photo_product', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFromProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('toc', models.TextField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_product', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Product photo')),
                ('video_yt', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('es', 'Espanol'), ('en', 'Ingles')], default='es', max_length=2, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('review_top5', models.TextField(blank=True, max_length=200, null=True)),
                ('year', models.DateField(blank=True, default='2020', null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=350, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ml_status', models.CharField(blank=True, choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=15, null=True)),
                ('ml_lowest_price', models.IntegerField(blank=True, null=True)),
                ('ml_view_count', models.IntegerField(blank=True, null=True)),
                ('ml_sold_count', models.IntegerField(blank=True, null=True)),
                ('ml_messages', models.IntegerField(blank=True, null=True)),
                ('ml_listing_type', models.CharField(blank=True, choices=[('gold_pro', 'Premium'), ('gold_premium', 'Oro Premium'), ('gold_special', 'Clásica'), ('gold', 'Oro'), ('silver', 'Plata'), ('bronze', 'Bronce'), ('free', 'Gratuita')], default='gold_special', max_length=15, null=True)),
                ('my_status', models.CharField(blank=True, choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=15, null=True)),
                ('available_quantity', models.IntegerField(blank=True, default=999, null=True)),
                ('remote_url_file', models.URLField(blank=True, max_length=350, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ml_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mlcategory')),
                ('ml_decription_tpl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mldescriptiontpl')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productfromprovider')),
            ],
        ),
    ]
