# Generated by Django 3.1.7 on 2021-02-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='ml_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Questions'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mlcategory', verbose_name='ML Category'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_decription_tpl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mldescriptiontpl', verbose_name='Description Tpl'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ML Id'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_listing_type',
            field=models.CharField(blank=True, choices=[('gold_pro', 'Premium'), ('gold_premium', 'Oro Premium'), ('gold_special', 'Clasica'), ('gold', 'Oro'), ('silver', 'Plata'), ('bronze', 'Bronce'), ('free', 'Gratuita')], default='gold_special', max_length=15, null=True, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_lowest_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='ML Lowest Price'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_messages',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Messages'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_sold_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Sold'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=15, null=True, verbose_name='ML Status'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='ml_view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Views'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='my_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=15, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productfromprovider',
            name='review_top5',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Reviews (Top 5)'),
        ),
        migrations.AlterField(
            model_name='productfromprovider',
            name='toc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Table of Contents'),
        ),
        migrations.AlterField(
            model_name='productfromprovider',
            name='video_yt',
            field=models.URLField(blank=True, null=True, verbose_name='YT Video'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='photo_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='photo_product',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Product Box'),
        ),
    ]
